# Generated by Django 3.0.4 on 2021-07-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pds',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='pds',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='pds',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='pds',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='pds',
            name='supprimer',
        ),
        migrations.AddField(
            model_name='pds',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pds',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pds',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pds',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pds',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pds',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
